#!/usr/bin/env python3
"""A minimal two-pass PDP-11 assembler for probes (no external toolchain).

Just enough to hand-write control-flow probes with labels instead of computing
branch offsets by hand. Emits the headless/oracle image format on stdout.

Programs are built with an Asm object:
    a = Asm(org=0o1000)
    a.mov_imm(0, 5)              # MOV #5, R0
    a.label("loop")
    a.two("ADD", (0,0), (1,0))   # ADD R0, R1   (reg, mode)
    a.sob(0, "loop")
    a.halt()
    a.emit(run=500, dumps=[(0o2000, 4)])
"""
import sys

# Double-operand opcode -> top nibble.
TWO = {"MOV": 0o1, "CMP": 0o2, "BIT": 0o3, "BIC": 0o4, "BIS": 0o5, "ADD": 0o6,
       "MOVB": 0o11, "CMPB": 0o12, "BITB": 0o13, "BICB": 0o14, "BISB": 0o15,
       "SUB": 0o16}
# Single-operand opcode -> 10-bit code (bits 15-6).
ONE = {"CLR": 0o0050, "COM": 0o0051, "INC": 0o0052, "DEC": 0o0053,
       "NEG": 0o0054, "ADC": 0o0055, "SBC": 0o0056, "TST": 0o0057,
       "ROR": 0o0060, "ROL": 0o0061, "ASR": 0o0062, "ASL": 0o0063,
       "SWAB": 0o0003, "SXT": 0o0067, "JMP": 0o0001}
# Branch mnemonic -> high byte.
BR = {"BR": 0o001, "BNE": 0o002, "BEQ": 0o003, "BGE": 0o004, "BLT": 0o005,
      "BGT": 0o006, "BLE": 0o007, "BPL": 0o200, "BMI": 0o201, "BHI": 0o202,
      "BLOS": 0o203, "BVC": 0o204, "BVS": 0o205, "BCC": 0o206, "BCS": 0o207}


def ea(operand):
    """operand = (reg, mode[, extra]) -> (6-bit spec, [extra words])."""
    reg, mode = operand[0], operand[1]
    spec = (mode << 3) | reg
    extra = [operand[2] & 0o177777] if len(operand) > 2 else []
    return spec, extra


class Asm:
    def __init__(self, org=0o1000):
        self.org = org
        self.items = []   # (kind, payload); resolved in pass 2
        self.labels = {}
        self.addr = org

    def _emit(self, nwords, fn):
        self.items.append((self.addr, nwords, fn))
        self.addr += nwords * 2

    def label(self, name):
        self.labels[name] = self.addr

    def word(self, w):
        self._emit(1, lambda L, a: [w & 0o177777])

    def mov_imm(self, reg, value):
        self._emit(2, lambda L, a: [0o012700 | (reg & 7), value & 0o177777])

    def mov_label(self, reg, target):
        # MOV #addr(target), Rreg
        self._emit(2, lambda L, a: [0o012700 | (reg & 7), L[target] & 0o177777])

    def two(self, op, src, dst):
        sspec, sx = ea(src)
        dspec, dx = ea(dst)
        top = TWO[op]
        words = [(top << 12) | (sspec << 6) | dspec] + sx + dx
        self._emit(len(words), lambda L, a: words)

    def one(self, op, dst):
        dspec, dx = ea(dst)
        code = ONE[op]
        words = [(code << 6) | dspec] + dx
        self._emit(len(words), lambda L, a: words)

    def branch(self, op, target):
        hb = BR[op]

        def fn(L, addr_after):
            off = (L[target] - addr_after) // 2
            assert -128 <= off <= 127, f"{op} to {target} out of range ({off})"
            return [(hb << 8) | (off & 0o377)]
        self._emit(1, fn)

    def sob(self, reg, target):
        def fn(L, addr_after):
            off = (addr_after - L[target]) // 2   # SOB branches backward
            assert 0 <= off <= 63, f"SOB to {target} out of range ({off})"
            return [0o077000 | ((reg & 7) << 6) | off]
        self._emit(1, fn)

    def jsr(self, reg, target):
        # JSR reg, target  via PC-relative (mode 6, R7).
        def fn(L, addr_after):
            off = (L[target] - addr_after) & 0o177777
            return [0o004000 | ((reg & 7) << 6) | 0o67, off]
        self._emit(2, fn)

    def rts(self, reg):
        self._emit(1, lambda L, a: [0o000200 | (reg & 7)])

    def push_imm(self, value):
        # MOV #value, -(R6)
        self._emit(2, lambda L, a: [0o012746, value & 0o177777])

    def push_label(self, target):
        # MOV #addr(target), -(R6)
        self._emit(2, lambda L, a: [0o012746, L[target] & 0o177777])

    def ccop(self, word):
        self._emit(1, lambda L, a: [word & 0o177777])

    # EIS: op reg, src   (reg = bits 8-6, src = 6-bit operand in bits 5-0)
    _EIS = {"MUL": 0o070000, "DIV": 0o071000, "ASH": 0o072000,
            "ASHC": 0o073000, "XOR": 0o074000}

    def eis(self, op, reg, src):
        sspec, sx = ea(src)
        words = [self._EIS[op] | ((reg & 7) << 6) | sspec] + sx
        self._emit(len(words), lambda L, a: words)

    def mfps(self, dst):
        # MFPS dst  (1067DD) — move PSW low byte to dst
        dspec, dx = ea(dst)
        words = [0o106700 | dspec] + dx
        self._emit(len(words), lambda L, a: words)

    def halt(self):
        self._emit(1, lambda L, a: [0])

    def emit(self, run=500, dumps=None):
        print("# generated by tools/probes/asm.py")
        print(f"pc {self.org:o}")
        for addr, nwords, fn in self.items:
            words = fn(self.labels, addr + nwords * 2)
            for i, w in enumerate(words):
                print(f"w {addr + i * 2:o} {w & 0o177777:o}")
        print(f"run {run}")
        for base, count in (dumps or []):
            print(f"dump {base:o} {count:o}")
