#!/usr/bin/env python3
"""Generate an ALU/flags probe image for the headless frontend and SimH oracle.

Emits a deterministic battery of single- and double-operand instructions over
registers R0-R5 (register-direct operands keep it self-contained — no memory
faults, no control flow). Both our core and SimH execute the identical words, so
diffing the final register+PSW state validates our condition-code semantics
against the oracle. Values are chosen to hit flag edges: 0, -1, min-negative
(0100000), max-positive (0077777), and a byte-sign boundary (0000200).

Usage:  gen_alu_probe.py > tests/images/alu.image
"""
import sys

LOAD = 0o1000  # program load address


def mov_imm(reg, value):
    """MOV #value, Rreg  ->  two words."""
    return [0o012700 | reg, value & 0o177777]


def two_op(top, sreg, dreg):
    """Register-direct double operand: op Rs, Rd."""
    return [(top << 12) | (sreg << 6) | dreg]


def one_op(code9, reg, byte=False):
    """Register-direct single operand: op Rreg."""
    return [((code9 | (0o1000 if byte else 0)) << 6) | reg]


def main():
    words = []

    # Preamble: edge-case seed values in R0..R5.
    seeds = [0o000001, 0o177777, 0o100000, 0o077777, 0o000200, 0o000005]
    for r, v in enumerate(seeds):
        words += mov_imm(r, v)

    # Double-operand battery (word). tops: MOV1 CMP2 BIT3 BIC4 BIS5 ADD6 SUB016.
    for top in (0o1, 0o2, 0o3, 0o4, 0o5, 0o6, 0o16):
        words += two_op(top, 0, 1)
        words += two_op(top, 2, 3)
        words += two_op(top, 4, 5)

    # Byte double-operand: MOVB011 CMPB012 BITB013 BICB014 BISB015.
    for top in (0o11, 0o12, 0o13, 0o14, 0o15):
        words += two_op(top, 1, 2)
        words += two_op(top, 3, 4)

    # Single-operand battery (word), each hitting a couple of registers.
    for code in (0o050, 0o051, 0o052, 0o053, 0o054, 0o055, 0o056, 0o057,
                 0o060, 0o061, 0o062, 0o063, 0o003, 0o067):
        words += one_op(code, 0)
        words += one_op(code, 3)

    # Single-operand battery (byte): CLRB..ASLB.
    for code in (0o050, 0o051, 0o052, 0o053, 0o054, 0o055, 0o056, 0o057,
                 0o060, 0o061, 0o062, 0o063):
        words += one_op(code, 1, byte=True)
        words += one_op(code, 4, byte=True)

    words += [0o000000]  # HALT

    print("# ALU/flags probe (generated by gen_alu_probe.py)")
    print(f"pc {LOAD:o}")
    addr = LOAD
    for w in words:
        print(f"w {addr:o} {w & 0o177777:o}")
        addr += 2
    print("run 500")
    return 0


if __name__ == "__main__":
    sys.exit(main())
